### ISSUE TITLE
question about the resistors.

### ISSUE THREAD

**Issue by aluqard89** [famicomical/MB9X-UART#1]
I was going to build this board but i see that the components of R1 and R2 is missing in the BOM.csv.
So what iam asking for is what values are the resistors?

**Comment by famicomical** [comment]
depends how bright you want your LED's to be. 330 to 1k ohm should be OK. most people who own a soldering iron would have some through hole resistors lying around so i didn't include them on the BOM.

**Comment by aluqard89** [comment]
Thanks for the answer ,appreciate it 👍
